const articlesData = [
  {
    title: "L.SANIC",
    description: "Гидрофильное масло-пенка для лица с муцином улитки, 120мл",
    price: 50.3,
    id: 1,
    img: "img1.jpg",
    count: 1,
  },
  {
    title: "Etude House",
    description: "Пенка для умывания и глубокой очистки, 160мл",
    price: 40,
    id: 2,
    img: "img2.jpg",
    count: 1,
  },
  {
    title: "LA MISO",
    description: "Пенка для глубокого очищения Мягкая кислородная PH 5.5, 150мл",
    price: 37.20,
    id: 3,
    img: "img3.jpg",
    count: 1,
  },
  {
    title: "A`PIEU",
    description: "Пенка для умывания с мадекассосидом, 130мл",
    price: 35.90,
    id: 4,
    img: "img4.jpg",
    count: 1,
  },
  {
    title: "MAYISLAND",
    description: "Пенка для лица Очищающая для проблемной кожи с экстрактом центеллы, 30мл",
    price: 10.90,
    id: 5,
    img: "img5.jpg",
    count: 1,
  },
  {
    title: "FRUDIA",
    description: "Пенка для умывания с гранатом, 145 г",
    price: 35.50,
    id: 6,
    img: "img6.jpg",
    count: 1,
  },
  {
    title: "NEXTBEAU",
    description: "Омолаживающий отшелушивающий гель для лица с гидролизованным коллагеном Collagen Solution Intensive Peeling Gel, 100 мл",
    price: 29.90,
    id: 7,
    img: "img7.jpg",
    count: 1,
  },
  {
    title: "Elizavecca",
    description: "Пенка-маска для умывания Milky Piggy Elastic Pore Cleansing Foam, 120 мл",
    price: 33.20,
    id: 8,
    img: "img8.jpg",
    count: 1,
  },
];

export default articlesData;
